# This file is used by BinderHub to specify Conda software dependencies for the custom environment.
# The example below only specifies a minimum Python version
name: base
channels:
  - defaults
dependencies:
  - python>=3.6
